// <copyright file="TaskEntity.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace TodoList.Services.Db.Entity
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using TodoListApp.Services.Db.Entity;

    /// <summary>
    /// Represents a Todo List item entity in the database. Each instance corresponds to a row in the Todo List table.
    /// </summary>
    public class TaskEntity
    {
        /// <summary>
        /// Gets or sets the unique identifier for the Todo List item. This field is automatically generated by the database upon insertion.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the title of the task.
        /// </summary>
        public string? Title { get; set; }

        /// <summary>
        /// Gets or sets a detailed description of the task.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the task was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Gets or sets the due date and time by which the task should be completed.
        /// </summary>
        public DateTime DueDate { get; set; }

        /// <summary>
        /// Gets or sets the current status of the task, represented as a <see cref="TaskStatus"/> enum value.
        /// </summary>
        public TaskStatus TaskStatus { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the user who created the task.
        /// </summary>
        public int CreatedById { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the user to whom the task is assigned.
        /// This property acts as a foreign key referencing the UserEntity.
        /// </summary>
        [ForeignKey("Assignee")]
        public int TaskAssigneeId { get; set; }

        /// <summary>
        /// Gets or sets navigation property for the user to whom the task is assigned.
        /// </summary>
        public UserEntity? Assignee { get; set; }

        /// <summary>
        /// Gets or sets the identifier of the user to whom the task is assigned.
        /// This property acts as a foreign key referencing the UserEntity.
        /// </summary>
        [ForeignKey("TodoList")]
        public int TodoListId { get; set; }

        /// <summary>
        /// Gets or sets navigation property for the user to whom the task is assigned.
        /// </summary>
        public TodoListEntity? TodoList { get; set; }
    }
}
