// <copyright file="TodoListEntity.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace TodoListApp.Services.Db.Entity
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Represents a Todo List item entity in the database. Each instance corresponds to a row in the Todo List table.
    /// </summary>
    public class TodoListEntity
    {
        /// <summary>
        /// Gets or sets the unique identifier for the Todo List item. This field is automatically generated by the database upon insertion.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the title of the Todo List item. This field represents the task or item to be completed.
        /// </summary>
        public string? Title { get; set; }

        /// <summary>
        /// Gets or sets the Description of the Todo List item. This field represents the task or item to be completed.
        /// </summary>
        public string? Description { get; set; }
    }
}
