// <copyright file="TodoListEntity.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace TodoListApp.Services.Db.Entity
{
    using System.ComponentModel.DataAnnotations;
    using TodoList.Services.Db.Entity;

    /// <summary>
    /// Represents a Todo List item entity in the database. Each instance corresponds to a row in the Todo List table.
    /// </summary>
    public class TodoListEntity
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TodoListEntity"/> class.
        /// </summary>
        /// <param name="id">TodoList Id.</param>
        /// <param name="title">TodoList Title.</param>
        /// <param name="description">TodoList Description.</param>
        public TodoListEntity(string? title, string? description)
        {
            this.Title = title;
            this.Description = description;
        }

        /// <summary>
        /// Gets or sets the unique identifier for the Todo List item. This field is automatically generated by the database upon insertion.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the title of the Todo List item. This field represents the task or item to be completed.
        /// </summary>
        public string? Title { get; set; }

        /// <summary>
        /// Gets or sets the Description of the Todo List item. This field represents the task or item to be completed.
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Gets or sets the list of Tasks of the Todo List item. This field represents the task or item to be completed.
        /// </summary>
        public ICollection<TaskEntity>? Tasks { get; set; }

        /// <summary>
        /// Updates TodoList instance.
        /// </summary>
        /// <param name="title">Title.</param>
        /// <param name="description">Description.</param>
        public void Update(string? title, string? description)
        {
            this.Title = title;
            this.Description = description;
        }
    }
}
